trigger:
  #  batch: true
  branches:
    include:
      - '*'
    exclude:
      - dependabot/*
      - renovate/*

schedules:
  - cron: "0 12 * * 6"
    displayName: Weekly Saturday build
    branches:
      include:
        - master
        - dev
    always: true

stages:
  - stage: Lint
    jobs:
      - template: ./templates/jobs/prepare.yaml
  - stage: Test
    jobs:
      - template: ./templates/jobs/test-app.yaml
  - stage: Build
    jobs:
      - template: ./templates/jobs/build-docs.yaml
